// <auto-generated />
using System;
using AptMgmtPortalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AptMgmtPortalAPI.Migrations.SqlServerMigrations
{
    [DbContext(typeof(AptMgmtDbContext))]
    [Migration("20200531010626_seedData")]
    partial class seedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.Agreement", b =>
                {
                    b.Property<int>("AgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgreementId");

                    b.ToTable("Agreements");

                    b.HasData(
                        new
                        {
                            AgreementId = 1,
                            Text = "This is a really long lease agreement text",
                            Title = "Lease Agreement"
                        },
                        new
                        {
                            AgreementId = 2,
                            Text = "This is a really long utility agreement text",
                            Title = "Utility Agreement"
                        },
                        new
                        {
                            AgreementId = 3,
                            Text = "This is a really long internet connection agreement text",
                            Title = "Internet Connection Agreement"
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.BillingPeriod", b =>
                {
                    b.Property<int>("BillingPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PeriodEnd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<string>("PeriodStart")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.HasKey("BillingPeriodId");

                    b.ToTable("BillingPeriods");

                    b.HasData(
                        new
                        {
                            BillingPeriodId = 1,
                            PeriodEnd = "2020-05-30 18:06:25.3625779",
                            PeriodStart = "2020-04-30 18:06:25.3518605"
                        },
                        new
                        {
                            BillingPeriodId = 2,
                            PeriodEnd = "2020-05-30 18:06:25.3626418",
                            PeriodStart = "2020-03-01 18:06:25.3518605"
                        },
                        new
                        {
                            BillingPeriodId = 3,
                            PeriodEnd = "2020-05-30 18:06:25.362645",
                            PeriodStart = "2019-12-02 18:06:25.3518605"
                        },
                        new
                        {
                            BillingPeriodId = 4,
                            PeriodEnd = "2020-05-30 18:06:25.362646",
                            PeriodStart = "2019-06-05 18:06:25.3518605"
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.MaintenanceRequest", b =>
                {
                    b.Property<int>("MaintenanceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CloseReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClosingUserId")
                        .HasColumnType("int");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaintenanceRequestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpeningUserId")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeClosed")
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<string>("TimeOpened")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<string>("UnitNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaintenanceRequestId");

                    b.ToTable("MaintenanceRequests");

                    b.HasData(
                        new
                        {
                            MaintenanceRequestId = 1,
                            CloseReason = "Completed",
                            ClosingUserId = 1,
                            InternalNotes = "Call Plumber",
                            MaintenanceRequestType = "Plumbing",
                            OpenNotes = "No water",
                            OpeningUserId = 1,
                            ResolutionNotes = "Fully restored.",
                            TimeClosed = "2020-05-30 18:06:25.3622374",
                            TimeOpened = "2020-03-01 18:06:25.3518605",
                            UnitNumber = "101"
                        },
                        new
                        {
                            MaintenanceRequestId = 2,
                            CloseReason = "Completed",
                            ClosingUserId = 1,
                            InternalNotes = "Call Comcast",
                            OpenNotes = "No Interet",
                            OpeningUserId = 1,
                            TimeOpened = "2020-03-01 18:06:25.3518605",
                            UnitNumber = "101"
                        },
                        new
                        {
                            MaintenanceRequestId = 3,
                            CloseReason = "CanceledByManagement",
                            ClosingUserId = 1,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 1,
                            TimeOpened = "2019-12-02 18:06:25.3518605",
                            UnitNumber = "101"
                        },
                        new
                        {
                            MaintenanceRequestId = 4,
                            CloseReason = "CanceledByTenant",
                            ClosingUserId = 1,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 2,
                            TimeOpened = "2020-03-01 18:06:25.3518605",
                            UnitNumber = "102"
                        },
                        new
                        {
                            MaintenanceRequestId = 5,
                            CloseReason = "CanceledByManagement",
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 3,
                            TimeOpened = "2020-03-01 18:06:25.3518605",
                            UnitNumber = "103"
                        },
                        new
                        {
                            MaintenanceRequestId = 6,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 4,
                            TimeOpened = "2020-03-01 18:06:25.3518605",
                            UnitNumber = "104"
                        },
                        new
                        {
                            MaintenanceRequestId = 7,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 5,
                            TimeOpened = "2020-03-01 18:06:25.3518605",
                            UnitNumber = "105"
                        },
                        new
                        {
                            MaintenanceRequestId = 8,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 6,
                            TimeOpened = "2020-03-01 18:06:25.3518605",
                            UnitNumber = "106"
                        },
                        new
                        {
                            MaintenanceRequestId = 9,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 7,
                            TimeOpened = "2020-03-01 18:06:25.3518605",
                            UnitNumber = "107"
                        },
                        new
                        {
                            MaintenanceRequestId = 10,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 8,
                            TimeOpened = "2020-03-01 18:06:25.3518605",
                            UnitNumber = "108"
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BillingPeriodId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TimePaid")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3615499"
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616084"
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616119"
                        },
                        new
                        {
                            PaymentId = 4,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.361613"
                        },
                        new
                        {
                            PaymentId = 5,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616139"
                        },
                        new
                        {
                            PaymentId = 6,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616148"
                        },
                        new
                        {
                            PaymentId = 7,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616157"
                        },
                        new
                        {
                            PaymentId = 8,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616166"
                        },
                        new
                        {
                            PaymentId = 9,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616176"
                        },
                        new
                        {
                            PaymentId = 10,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616185"
                        },
                        new
                        {
                            PaymentId = 11,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616194"
                        },
                        new
                        {
                            PaymentId = 12,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616203"
                        },
                        new
                        {
                            PaymentId = 13,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616212"
                        },
                        new
                        {
                            PaymentId = 14,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616221"
                        },
                        new
                        {
                            PaymentId = 15,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616231"
                        },
                        new
                        {
                            PaymentId = 16,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.361624"
                        },
                        new
                        {
                            PaymentId = 17,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616249"
                        },
                        new
                        {
                            PaymentId = 18,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616258"
                        },
                        new
                        {
                            PaymentId = 19,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616267"
                        },
                        new
                        {
                            PaymentId = 20,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616277"
                        },
                        new
                        {
                            PaymentId = 21,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616286"
                        },
                        new
                        {
                            PaymentId = 22,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616295"
                        },
                        new
                        {
                            PaymentId = 23,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616304"
                        },
                        new
                        {
                            PaymentId = 24,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616313"
                        },
                        new
                        {
                            PaymentId = 25,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616322"
                        },
                        new
                        {
                            PaymentId = 26,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616332"
                        },
                        new
                        {
                            PaymentId = 27,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616341"
                        },
                        new
                        {
                            PaymentId = 28,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.361635"
                        },
                        new
                        {
                            PaymentId = 29,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616359"
                        },
                        new
                        {
                            PaymentId = 30,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616368"
                        },
                        new
                        {
                            PaymentId = 31,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616377"
                        },
                        new
                        {
                            PaymentId = 32,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616386"
                        },
                        new
                        {
                            PaymentId = 33,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616396"
                        },
                        new
                        {
                            PaymentId = 34,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616405"
                        },
                        new
                        {
                            PaymentId = 35,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616414"
                        },
                        new
                        {
                            PaymentId = 36,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616423"
                        },
                        new
                        {
                            PaymentId = 37,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616432"
                        },
                        new
                        {
                            PaymentId = 38,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616442"
                        },
                        new
                        {
                            PaymentId = 39,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616451"
                        },
                        new
                        {
                            PaymentId = 40,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.361646"
                        },
                        new
                        {
                            PaymentId = 41,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616469"
                        },
                        new
                        {
                            PaymentId = 42,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616479"
                        },
                        new
                        {
                            PaymentId = 43,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616488"
                        },
                        new
                        {
                            PaymentId = 44,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616497"
                        },
                        new
                        {
                            PaymentId = 45,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.361665"
                        },
                        new
                        {
                            PaymentId = 46,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616662"
                        },
                        new
                        {
                            PaymentId = 47,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616671"
                        },
                        new
                        {
                            PaymentId = 48,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.361668"
                        },
                        new
                        {
                            PaymentId = 49,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.361669"
                        },
                        new
                        {
                            PaymentId = 50,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 1,
                            TimePaid = "2020-05-30 18:06:25.3616699"
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.ResourceUsageRate", b =>
                {
                    b.Property<int>("ResourceUsageRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PeriodEnd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<string>("PeriodStart")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.HasKey("ResourceUsageRateId");

                    b.ToTable("ResourceUsageRates");

                    b.HasData(
                        new
                        {
                            ResourceUsageRateId = 1,
                            PeriodEnd = "2020-05-30 18:06:25.3611618",
                            PeriodStart = "2020-03-01 18:06:25.3518605",
                            Rate = 40.450000000000003,
                            ResourceType = 2
                        },
                        new
                        {
                            ResourceUsageRateId = 2,
                            PeriodEnd = "2020-05-30 18:06:25.3612618",
                            PeriodStart = "2020-03-01 18:06:25.3518605",
                            Rate = 30.449999999999999,
                            ResourceType = 0
                        },
                        new
                        {
                            ResourceUsageRateId = 3,
                            PeriodEnd = "2020-05-30 18:06:25.3612714",
                            PeriodStart = "2020-03-01 18:06:25.3518605",
                            Rate = 1100.0,
                            ResourceType = 4
                        },
                        new
                        {
                            ResourceUsageRateId = 4,
                            PeriodEnd = "2020-05-30 18:06:25.3612724",
                            PeriodStart = "2020-03-01 18:06:25.3518605",
                            Rate = 20.550000000000001,
                            ResourceType = 3
                        },
                        new
                        {
                            ResourceUsageRateId = 5,
                            PeriodEnd = "2020-05-30 18:06:25.3612733",
                            PeriodStart = "2020-03-01 18:06:25.3518605",
                            Rate = 15.75,
                            ResourceType = 1
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.SignedAgreement", b =>
                {
                    b.Property<int>("SignedAgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgreementId")
                        .HasColumnType("int");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<string>("SignedDate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("SignedAgreementId");

                    b.ToTable("SignedAgreements");

                    b.HasData(
                        new
                        {
                            SignedAgreementId = 1,
                            AgreementId = 1,
                            EndDate = "2020-05-30 18:06:25.3608289",
                            SignedDate = "2020-03-01 18:06:25.3518605",
                            StartDate = "2020-03-01 18:06:25.3518605",
                            TenantId = 1
                        },
                        new
                        {
                            SignedAgreementId = 2,
                            AgreementId = 2,
                            EndDate = "2020-05-30 18:06:25.3609185",
                            SignedDate = "2019-12-02 18:06:25.3518605",
                            StartDate = "2019-12-02 18:06:25.3518605",
                            TenantId = 2
                        },
                        new
                        {
                            SignedAgreementId = 3,
                            AgreementId = 3,
                            EndDate = "2020-05-30 18:06:25.3609237",
                            SignedDate = "2019-06-05 18:06:25.3518605",
                            StartDate = "2019-06-05 18:06:25.3518605",
                            TenantId = 3
                        },
                        new
                        {
                            SignedAgreementId = 4,
                            AgreementId = 4,
                            EndDate = "2020-05-30 18:06:25.3609248",
                            SignedDate = "2020-03-01 18:06:25.3518605",
                            StartDate = "2020-03-01 18:06:25.3518605",
                            TenantId = 4
                        },
                        new
                        {
                            SignedAgreementId = 5,
                            AgreementId = 5,
                            EndDate = "2020-05-30 18:06:25.3609258",
                            SignedDate = "2019-12-02 18:06:25.3518605",
                            StartDate = "2019-12-02 18:06:25.3518605",
                            TenantId = 5
                        },
                        new
                        {
                            SignedAgreementId = 6,
                            AgreementId = 6,
                            EndDate = "2020-05-30 18:06:25.3609267",
                            SignedDate = "2019-06-05 18:06:25.3518605",
                            StartDate = "2019-06-05 18:06:25.3518605",
                            TenantId = 6
                        },
                        new
                        {
                            SignedAgreementId = 7,
                            AgreementId = 7,
                            EndDate = "2020-05-30 18:06:25.3609276",
                            SignedDate = "2020-03-01 18:06:25.3518605",
                            StartDate = "2020-03-01 18:06:25.3518605",
                            TenantId = 7
                        },
                        new
                        {
                            SignedAgreementId = 8,
                            AgreementId = 8,
                            EndDate = "2020-05-30 18:06:25.3609286",
                            SignedDate = "2019-12-02 18:06:25.3518605",
                            StartDate = "2019-12-02 18:06:25.3518605",
                            TenantId = 8
                        },
                        new
                        {
                            SignedAgreementId = 9,
                            AgreementId = 9,
                            EndDate = "2020-05-30 18:06:25.3609295",
                            SignedDate = "2019-06-05 18:06:25.3518605",
                            StartDate = "2019-06-05 18:06:25.3518605",
                            TenantId = 9
                        },
                        new
                        {
                            SignedAgreementId = 10,
                            AgreementId = 10,
                            EndDate = "2020-05-30 18:06:25.3609304",
                            SignedDate = "2020-03-01 18:06:25.3518605",
                            StartDate = "2020-03-01 18:06:25.3518605",
                            TenantId = 10
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = 1,
                            Email = "jayson@gmail.com",
                            FirstName = "Jayson",
                            LastName = "Lennon",
                            PhoneNumber = "555-1604-317",
                            UserId = 4
                        },
                        new
                        {
                            TenantId = 2,
                            Email = "david@gmail.com",
                            FirstName = "David",
                            LastName = "Sawyer",
                            PhoneNumber = "555-1958-162",
                            UserId = 5
                        },
                        new
                        {
                            TenantId = 3,
                            Email = "michael@gmail.com",
                            FirstName = "Michael",
                            LastName = "Walker",
                            PhoneNumber = "555-3115-412",
                            UserId = 6
                        },
                        new
                        {
                            TenantId = 4,
                            Email = "sulav@gmail.com",
                            FirstName = "Sulav",
                            LastName = "Aryal",
                            PhoneNumber = "555-7873-595",
                            UserId = 7
                        },
                        new
                        {
                            TenantId = 5,
                            Email = "melvin@gmail.com",
                            FirstName = "Melvin",
                            LastName = "Johnson",
                            PhoneNumber = "555-2858-445",
                            UserId = 8
                        },
                        new
                        {
                            TenantId = 6,
                            Email = "deon@gmail.com",
                            FirstName = "Deon ",
                            LastName = "Smith",
                            PhoneNumber = "555-5140-298",
                            UserId = 9
                        },
                        new
                        {
                            TenantId = 7,
                            Email = "ruth@gmail.com",
                            FirstName = "Ruth ",
                            LastName = "Williams",
                            PhoneNumber = "555-3037-777",
                            UserId = 10
                        },
                        new
                        {
                            TenantId = 8,
                            Email = "frances@gmail.com",
                            FirstName = "Frances ",
                            LastName = "Hook",
                            PhoneNumber = "555-9871-503",
                            UserId = 11
                        },
                        new
                        {
                            TenantId = 9,
                            Email = "linda@gmail.com",
                            FirstName = "Linda",
                            LastName = "Lopez",
                            PhoneNumber = "555-6027-558",
                            UserId = 12
                        },
                        new
                        {
                            TenantId = 10,
                            Email = "regina@gmail.com",
                            FirstName = "Regina",
                            LastName = "McCoy",
                            PhoneNumber = "555-5304-625",
                            UserId = 13
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.TenantResourceUsage", b =>
                {
                    b.Property<int>("TenantResourceUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<string>("SampleTime")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<double>("UsageAmount")
                        .HasColumnType("float");

                    b.HasKey("TenantResourceUsageId");

                    b.ToTable("TenantResourceUsages");

                    b.HasData(
                        new
                        {
                            TenantResourceUsageId = 1,
                            ResourceType = 2,
                            SampleTime = "2020-05-30 18:06:25.3603893",
                            TenantId = 1,
                            UsageAmount = 100.0
                        },
                        new
                        {
                            TenantResourceUsageId = 2,
                            ResourceType = 0,
                            SampleTime = "2020-05-30 18:06:25.3604692",
                            TenantId = 1,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 3,
                            ResourceType = 4,
                            SampleTime = "2020-05-30 18:06:25.3604845",
                            TenantId = 1,
                            UsageAmount = 1100.5
                        },
                        new
                        {
                            TenantResourceUsageId = 4,
                            ResourceType = 3,
                            SampleTime = "2020-05-30 18:06:25.3604857",
                            TenantId = 1,
                            UsageAmount = 15.56
                        },
                        new
                        {
                            TenantResourceUsageId = 5,
                            ResourceType = 1,
                            SampleTime = "2020-05-30 18:06:25.3604866",
                            TenantId = 1,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 6,
                            ResourceType = 2,
                            SampleTime = "2020-05-30 18:06:25.3604875",
                            TenantId = 2,
                            UsageAmount = 100.0
                        },
                        new
                        {
                            TenantResourceUsageId = 7,
                            ResourceType = 0,
                            SampleTime = "2020-05-30 18:06:25.3604885",
                            TenantId = 2,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 8,
                            ResourceType = 4,
                            SampleTime = "2020-05-30 18:06:25.3604894",
                            TenantId = 2,
                            UsageAmount = 1100.5
                        },
                        new
                        {
                            TenantResourceUsageId = 9,
                            ResourceType = 3,
                            SampleTime = "2020-05-30 18:06:25.3604903",
                            TenantId = 2,
                            UsageAmount = 15.56
                        },
                        new
                        {
                            TenantResourceUsageId = 10,
                            ResourceType = 1,
                            SampleTime = "2020-05-30 18:06:25.3604912",
                            TenantId = 2,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 11,
                            ResourceType = 2,
                            SampleTime = "2020-05-30 18:06:25.3604921",
                            TenantId = 3,
                            UsageAmount = 100.0
                        },
                        new
                        {
                            TenantResourceUsageId = 12,
                            ResourceType = 0,
                            SampleTime = "2020-05-30 18:06:25.360493",
                            TenantId = 3,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 13,
                            ResourceType = 4,
                            SampleTime = "2020-05-30 18:06:25.3604939",
                            TenantId = 3,
                            UsageAmount = 1100.5
                        },
                        new
                        {
                            TenantResourceUsageId = 14,
                            ResourceType = 3,
                            SampleTime = "2020-05-30 18:06:25.3604948",
                            TenantId = 3,
                            UsageAmount = 15.56
                        },
                        new
                        {
                            TenantResourceUsageId = 15,
                            ResourceType = 1,
                            SampleTime = "2020-05-30 18:06:25.3604958",
                            TenantId = 3,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 16,
                            ResourceType = 2,
                            SampleTime = "2020-05-30 18:06:25.3604967",
                            TenantId = 4,
                            UsageAmount = 100.0
                        },
                        new
                        {
                            TenantResourceUsageId = 17,
                            ResourceType = 0,
                            SampleTime = "2020-05-30 18:06:25.3604976",
                            TenantId = 4,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 18,
                            ResourceType = 4,
                            SampleTime = "2020-05-30 18:06:25.3604985",
                            TenantId = 4,
                            UsageAmount = 1100.5
                        },
                        new
                        {
                            TenantResourceUsageId = 19,
                            ResourceType = 3,
                            SampleTime = "2020-05-30 18:06:25.3604994",
                            TenantId = 4,
                            UsageAmount = 15.56
                        },
                        new
                        {
                            TenantResourceUsageId = 20,
                            ResourceType = 1,
                            SampleTime = "2020-05-30 18:06:25.3605003",
                            TenantId = 4,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 21,
                            ResourceType = 2,
                            SampleTime = "2020-05-30 18:06:25.3605012",
                            TenantId = 5,
                            UsageAmount = 150.0
                        },
                        new
                        {
                            TenantResourceUsageId = 22,
                            ResourceType = 0,
                            SampleTime = "2020-05-30 18:06:25.3605022",
                            TenantId = 5,
                            UsageAmount = 60.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 23,
                            ResourceType = 4,
                            SampleTime = "2020-05-30 18:06:25.3605031",
                            TenantId = 5,
                            UsageAmount = 1200.5
                        },
                        new
                        {
                            TenantResourceUsageId = 24,
                            ResourceType = 3,
                            SampleTime = "2020-05-30 18:06:25.360504",
                            TenantId = 5,
                            UsageAmount = 20.559999999999999
                        },
                        new
                        {
                            TenantResourceUsageId = 25,
                            ResourceType = 1,
                            SampleTime = "2020-05-30 18:06:25.3605049",
                            TenantId = 5,
                            UsageAmount = 40.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 26,
                            ResourceType = 2,
                            SampleTime = "2020-05-30 18:06:25.3605058",
                            TenantId = 6,
                            UsageAmount = 150.0
                        },
                        new
                        {
                            TenantResourceUsageId = 27,
                            ResourceType = 0,
                            SampleTime = "2020-05-30 18:06:25.3605067",
                            TenantId = 6,
                            UsageAmount = 60.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 28,
                            ResourceType = 4,
                            SampleTime = "2020-05-30 18:06:25.3605076",
                            TenantId = 6,
                            UsageAmount = 1200.5
                        },
                        new
                        {
                            TenantResourceUsageId = 29,
                            ResourceType = 3,
                            SampleTime = "2020-05-30 18:06:25.3605085",
                            TenantId = 6,
                            UsageAmount = 25.559999999999999
                        },
                        new
                        {
                            TenantResourceUsageId = 30,
                            ResourceType = 1,
                            SampleTime = "2020-05-30 18:06:25.3605094",
                            TenantId = 6,
                            UsageAmount = 31.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 31,
                            ResourceType = 2,
                            SampleTime = "2020-05-30 18:06:25.3605104",
                            TenantId = 7,
                            UsageAmount = 100.0
                        },
                        new
                        {
                            TenantResourceUsageId = 32,
                            ResourceType = 0,
                            SampleTime = "2020-05-30 18:06:25.3605113",
                            TenantId = 7,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 33,
                            ResourceType = 4,
                            SampleTime = "2020-05-30 18:06:25.3605122",
                            TenantId = 7,
                            UsageAmount = 1100.5
                        },
                        new
                        {
                            TenantResourceUsageId = 34,
                            ResourceType = 3,
                            SampleTime = "2020-05-30 18:06:25.3605131",
                            TenantId = 7,
                            UsageAmount = 15.56
                        },
                        new
                        {
                            TenantResourceUsageId = 35,
                            ResourceType = 1,
                            SampleTime = "2020-05-30 18:06:25.360514",
                            TenantId = 7,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 36,
                            ResourceType = 2,
                            SampleTime = "2020-05-30 18:06:25.3605149",
                            TenantId = 8,
                            UsageAmount = 100.0
                        },
                        new
                        {
                            TenantResourceUsageId = 37,
                            ResourceType = 0,
                            SampleTime = "2020-05-30 18:06:25.3605159",
                            TenantId = 8,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 38,
                            ResourceType = 4,
                            SampleTime = "2020-05-30 18:06:25.3605168",
                            TenantId = 8,
                            UsageAmount = 1100.5
                        },
                        new
                        {
                            TenantResourceUsageId = 39,
                            ResourceType = 3,
                            SampleTime = "2020-05-30 18:06:25.3605177",
                            TenantId = 8,
                            UsageAmount = 15.56
                        },
                        new
                        {
                            TenantResourceUsageId = 40,
                            ResourceType = 1,
                            SampleTime = "2020-05-30 18:06:25.3605186",
                            TenantId = 8,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 41,
                            ResourceType = 2,
                            SampleTime = "2020-05-30 18:06:25.3605195",
                            TenantId = 9,
                            UsageAmount = 100.0
                        },
                        new
                        {
                            TenantResourceUsageId = 42,
                            ResourceType = 0,
                            SampleTime = "2020-05-30 18:06:25.3605204",
                            TenantId = 9,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 43,
                            ResourceType = 4,
                            SampleTime = "2020-05-30 18:06:25.3605213",
                            TenantId = 9,
                            UsageAmount = 1100.5
                        },
                        new
                        {
                            TenantResourceUsageId = 44,
                            ResourceType = 3,
                            SampleTime = "2020-05-30 18:06:25.3605222",
                            TenantId = 9,
                            UsageAmount = 15.56
                        },
                        new
                        {
                            TenantResourceUsageId = 45,
                            ResourceType = 1,
                            SampleTime = "2020-05-30 18:06:25.3605231",
                            TenantId = 9,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 46,
                            ResourceType = 2,
                            SampleTime = "2020-05-30 18:06:25.360524",
                            TenantId = 10,
                            UsageAmount = 100.0
                        },
                        new
                        {
                            TenantResourceUsageId = 47,
                            ResourceType = 0,
                            SampleTime = "2020-05-30 18:06:25.3605249",
                            TenantId = 10,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 48,
                            ResourceType = 4,
                            SampleTime = "2020-05-30 18:06:25.3605258",
                            TenantId = 10,
                            UsageAmount = 1100.5
                        },
                        new
                        {
                            TenantResourceUsageId = 49,
                            ResourceType = 3,
                            SampleTime = "2020-05-30 18:06:25.3605267",
                            TenantId = 10,
                            UsageAmount = 15.56
                        },
                        new
                        {
                            TenantResourceUsageId = 50,
                            ResourceType = 1,
                            SampleTime = "2020-05-30 18:06:25.3605276",
                            TenantId = 10,
                            UsageAmount = 30.329999999999998
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("UnitNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UnitId");

                    b.HasIndex("UnitNumber")
                        .IsUnique()
                        .HasFilter("[UnitNumber] IS NOT NULL");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            TenantId = 1,
                            UnitNumber = "101"
                        },
                        new
                        {
                            UnitId = 2,
                            TenantId = 2,
                            UnitNumber = "102"
                        },
                        new
                        {
                            UnitId = 3,
                            TenantId = 3,
                            UnitNumber = "103"
                        },
                        new
                        {
                            UnitId = 4,
                            TenantId = 4,
                            UnitNumber = "104"
                        },
                        new
                        {
                            UnitId = 5,
                            TenantId = 5,
                            UnitNumber = "105"
                        },
                        new
                        {
                            UnitId = 6,
                            TenantId = 6,
                            UnitNumber = "106"
                        },
                        new
                        {
                            UnitId = 7,
                            TenantId = 7,
                            UnitNumber = "107"
                        },
                        new
                        {
                            UnitId = 8,
                            TenantId = 8,
                            UnitNumber = "108"
                        },
                        new
                        {
                            UnitId = 9,
                            TenantId = 9,
                            UnitNumber = "109"
                        },
                        new
                        {
                            UnitId = 10,
                            TenantId = 10,
                            UnitNumber = "110"
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ApiKey = "test-key",
                            LoginName = "admin",
                            Password = "password",
                            UserAccountType = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            ApiKey = "test-key",
                            LoginName = "manager",
                            Password = "password",
                            UserAccountType = "Manager"
                        },
                        new
                        {
                            UserId = 3,
                            ApiKey = "test-key",
                            LoginName = "jayson",
                            Password = "password",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 4,
                            ApiKey = "test-key",
                            LoginName = "david",
                            Password = "password",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 5,
                            ApiKey = "test-key",
                            LoginName = "michael",
                            Password = "password",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 6,
                            ApiKey = "test-key",
                            LoginName = "sulav",
                            Password = "password",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 7,
                            ApiKey = "test-key",
                            LoginName = "melvin",
                            Password = "password",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 8,
                            ApiKey = "test-key",
                            LoginName = "deon",
                            Password = "password",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 9,
                            ApiKey = "test-key",
                            LoginName = "ruth",
                            Password = "password",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 10,
                            ApiKey = "test-key",
                            LoginName = "frances",
                            Password = "password",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 11,
                            ApiKey = "test-key",
                            LoginName = "linda",
                            Password = "password",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 12,
                            ApiKey = "test-key",
                            LoginName = "regina",
                            Password = "password",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 13,
                            ApiKey = "test-key",
                            LoginName = "sulav",
                            Password = "password",
                            UserAccountType = "Tenant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
