// <auto-generated />
using System;
using AptMgmtPortalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AptMgmtPortalAPI.Migrations.SqlServerMigrations
{
    [DbContext(typeof(AptMgmtDbContext))]
    partial class AptMgmtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.Agreement", b =>
                {
                    b.Property<int>("AgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AgreementId");

                    b.ToTable("Agreements");

                    b.HasData(
                        new
                        {
                            AgreementId = 1,
                            Text = "This is a really long lease agreement text",
                            Title = "Lease Agreement"
                        },
                        new
                        {
                            AgreementId = 2,
                            Text = "This is a really long utility agreement text",
                            Title = "Utility Agreement"
                        },
                        new
                        {
                            AgreementId = 3,
                            Text = "This is a really long internet connection agreement text",
                            Title = "Internet Connection Agreement"
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.BillingPeriod", b =>
                {
                    b.Property<int>("BillingPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PeriodEnd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<string>("PeriodStart")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.HasKey("BillingPeriodId");

                    b.ToTable("BillingPeriods");

                    b.HasData(
                        new
                        {
                            BillingPeriodId = 1,
                            PeriodEnd = "2020-06-03 21:37:25.5221353",
                            PeriodStart = "2020-05-03 21:37:25.5059952"
                        },
                        new
                        {
                            BillingPeriodId = 2,
                            PeriodEnd = "2020-06-03 21:37:25.5221802",
                            PeriodStart = "2020-03-04 21:37:25.5059952"
                        },
                        new
                        {
                            BillingPeriodId = 3,
                            PeriodEnd = "2020-06-03 21:37:25.522182",
                            PeriodStart = "2019-12-05 21:37:25.5059952"
                        },
                        new
                        {
                            BillingPeriodId = 4,
                            PeriodEnd = "2020-06-03 21:37:25.5221871",
                            PeriodStart = "2019-06-08 21:37:25.5059952"
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.MaintenanceRequest", b =>
                {
                    b.Property<int>("MaintenanceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CloseReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClosingUserId")
                        .HasColumnType("int");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaintenanceRequestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpeningUserId")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeClosed")
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<string>("TimeOpened")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<string>("UnitNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaintenanceRequestId");

                    b.ToTable("MaintenanceRequests");

                    b.HasData(
                        new
                        {
                            MaintenanceRequestId = 1,
                            CloseReason = "Completed",
                            ClosingUserId = 1,
                            InternalNotes = "Call Plumber",
                            MaintenanceRequestType = "Plumbing",
                            OpenNotes = "No water",
                            OpeningUserId = 1,
                            ResolutionNotes = "Fully restored.",
                            TimeClosed = "2020-06-02 21:37:25.521845",
                            TimeOpened = "2020-03-04 21:37:25.5059952",
                            UnitNumber = "101"
                        },
                        new
                        {
                            MaintenanceRequestId = 2,
                            CloseReason = "Completed",
                            ClosingUserId = 1,
                            InternalNotes = "Call Comcast",
                            OpenNotes = "No Interet",
                            OpeningUserId = 1,
                            ResolutionNotes = "Fixed",
                            TimeClosed = "2020-05-03 21:37:25.5059952",
                            TimeOpened = "2020-03-04 21:37:25.5059952",
                            UnitNumber = "101"
                        },
                        new
                        {
                            MaintenanceRequestId = 3,
                            CloseReason = "CanceledByManagement",
                            ClosingUserId = 1,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 1,
                            ResolutionNotes = "Fixed",
                            TimeClosed = "2020-05-03 21:37:25.5059952",
                            TimeOpened = "2019-12-05 21:37:25.5059952",
                            UnitNumber = "101"
                        },
                        new
                        {
                            MaintenanceRequestId = 4,
                            CloseReason = "CanceledByTenant",
                            ClosingUserId = 1,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 2,
                            ResolutionNotes = "Fixed",
                            TimeClosed = "2020-05-03 21:37:25.5059952",
                            TimeOpened = "2020-03-04 21:37:25.5059952",
                            UnitNumber = "102"
                        },
                        new
                        {
                            MaintenanceRequestId = 5,
                            CloseReason = "CanceledByManagement",
                            ClosingUserId = 2,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 3,
                            ResolutionNotes = "Fixed",
                            TimeClosed = "2020-05-03 21:37:25.5059952",
                            TimeOpened = "2020-03-04 21:37:25.5059952",
                            UnitNumber = "103"
                        },
                        new
                        {
                            MaintenanceRequestId = 6,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 4,
                            TimeOpened = "2020-03-04 21:37:25.5059952",
                            UnitNumber = "104"
                        },
                        new
                        {
                            MaintenanceRequestId = 7,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 5,
                            TimeOpened = "2020-03-04 21:37:25.5059952",
                            UnitNumber = "105"
                        },
                        new
                        {
                            MaintenanceRequestId = 8,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 6,
                            TimeOpened = "2020-03-04 21:37:25.5059952",
                            UnitNumber = "106"
                        },
                        new
                        {
                            MaintenanceRequestId = 9,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 7,
                            TimeOpened = "2020-03-04 21:37:25.5059952",
                            UnitNumber = "107"
                        },
                        new
                        {
                            MaintenanceRequestId = 10,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 8,
                            TimeOpened = "2020-03-04 21:37:25.5059952",
                            UnitNumber = "108"
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BillingPeriodId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TimePaid")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 1,
                            TimePaid = "2020-06-01 21:37:25.5213302"
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 1,
                            TimePaid = "2020-06-01 21:37:25.5213778"
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 1,
                            TimePaid = "2020-06-01 21:37:25.5213797"
                        },
                        new
                        {
                            PaymentId = 4,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 1,
                            TimePaid = "2020-06-01 21:37:25.52138"
                        },
                        new
                        {
                            PaymentId = 5,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 1,
                            TimePaid = "2020-06-01 21:37:25.5213802"
                        },
                        new
                        {
                            PaymentId = 6,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 2,
                            TimePaid = "2020-06-01 21:37:25.5213805"
                        },
                        new
                        {
                            PaymentId = 7,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 2,
                            TimePaid = "2020-06-01 21:37:25.5213807"
                        },
                        new
                        {
                            PaymentId = 8,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 2,
                            TimePaid = "2020-06-01 21:37:25.521381"
                        },
                        new
                        {
                            PaymentId = 9,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 2,
                            TimePaid = "2020-06-01 21:37:25.5213812"
                        },
                        new
                        {
                            PaymentId = 10,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 2,
                            TimePaid = "2020-06-01 21:37:25.5213814"
                        },
                        new
                        {
                            PaymentId = 11,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 3,
                            TimePaid = "2020-06-01 21:37:25.5213817"
                        },
                        new
                        {
                            PaymentId = 12,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 3,
                            TimePaid = "2020-06-01 21:37:25.5213819"
                        },
                        new
                        {
                            PaymentId = 13,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 3,
                            TimePaid = "2020-06-01 21:37:25.5213822"
                        },
                        new
                        {
                            PaymentId = 14,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 3,
                            TimePaid = "2020-06-01 21:37:25.5213824"
                        },
                        new
                        {
                            PaymentId = 15,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 3,
                            TimePaid = "2020-06-01 21:37:25.5213827"
                        },
                        new
                        {
                            PaymentId = 16,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 4,
                            TimePaid = "2020-06-01 21:37:25.5213829"
                        },
                        new
                        {
                            PaymentId = 17,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 4,
                            TimePaid = "2020-06-01 21:37:25.5213832"
                        },
                        new
                        {
                            PaymentId = 18,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 4,
                            TimePaid = "2020-06-01 21:37:25.5213834"
                        },
                        new
                        {
                            PaymentId = 19,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 4,
                            TimePaid = "2020-06-01 21:37:25.5213836"
                        },
                        new
                        {
                            PaymentId = 20,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 4,
                            TimePaid = "2020-06-01 21:37:25.521384"
                        },
                        new
                        {
                            PaymentId = 21,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 5,
                            TimePaid = "2020-06-01 21:37:25.5213842"
                        },
                        new
                        {
                            PaymentId = 22,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 5,
                            TimePaid = "2020-06-01 21:37:25.5213845"
                        },
                        new
                        {
                            PaymentId = 23,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 5,
                            TimePaid = "2020-06-01 21:37:25.5213847"
                        },
                        new
                        {
                            PaymentId = 24,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 5,
                            TimePaid = "2020-06-01 21:37:25.5213849"
                        },
                        new
                        {
                            PaymentId = 25,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 5,
                            TimePaid = "2020-06-01 21:37:25.5213852"
                        },
                        new
                        {
                            PaymentId = 26,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 6,
                            TimePaid = "2020-06-01 21:37:25.5213854"
                        },
                        new
                        {
                            PaymentId = 27,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 6,
                            TimePaid = "2020-06-01 21:37:25.5213856"
                        },
                        new
                        {
                            PaymentId = 28,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 6,
                            TimePaid = "2020-06-01 21:37:25.5213859"
                        },
                        new
                        {
                            PaymentId = 29,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 6,
                            TimePaid = "2020-06-01 21:37:25.5213861"
                        },
                        new
                        {
                            PaymentId = 30,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 6,
                            TimePaid = "2020-06-01 21:37:25.5213863"
                        },
                        new
                        {
                            PaymentId = 31,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 7,
                            TimePaid = "2020-06-01 21:37:25.5213866"
                        },
                        new
                        {
                            PaymentId = 32,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 7,
                            TimePaid = "2020-06-01 21:37:25.5213868"
                        },
                        new
                        {
                            PaymentId = 33,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 7,
                            TimePaid = "2020-06-01 21:37:25.521387"
                        },
                        new
                        {
                            PaymentId = 34,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 7,
                            TimePaid = "2020-06-01 21:37:25.5213873"
                        },
                        new
                        {
                            PaymentId = 35,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 7,
                            TimePaid = "2020-06-01 21:37:25.5213875"
                        },
                        new
                        {
                            PaymentId = 36,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 8,
                            TimePaid = "2020-06-01 21:37:25.5213877"
                        },
                        new
                        {
                            PaymentId = 37,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 8,
                            TimePaid = "2020-06-01 21:37:25.521388"
                        },
                        new
                        {
                            PaymentId = 38,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 8,
                            TimePaid = "2020-06-01 21:37:25.5213882"
                        },
                        new
                        {
                            PaymentId = 39,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 8,
                            TimePaid = "2020-06-01 21:37:25.5213884"
                        },
                        new
                        {
                            PaymentId = 40,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 8,
                            TimePaid = "2020-06-01 21:37:25.5213887"
                        },
                        new
                        {
                            PaymentId = 41,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 9,
                            TimePaid = "2020-06-01 21:37:25.5213889"
                        },
                        new
                        {
                            PaymentId = 42,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 9,
                            TimePaid = "2020-06-01 21:37:25.5213891"
                        },
                        new
                        {
                            PaymentId = 43,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 9,
                            TimePaid = "2020-06-01 21:37:25.5213894"
                        },
                        new
                        {
                            PaymentId = 44,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 9,
                            TimePaid = "2020-06-01 21:37:25.5213896"
                        },
                        new
                        {
                            PaymentId = 45,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 9,
                            TimePaid = "2020-06-01 21:37:25.5213898"
                        },
                        new
                        {
                            PaymentId = 46,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 10,
                            TimePaid = "2020-06-01 21:37:25.52139"
                        },
                        new
                        {
                            PaymentId = 47,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 10,
                            TimePaid = "2020-06-01 21:37:25.5213903"
                        },
                        new
                        {
                            PaymentId = 48,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 10,
                            TimePaid = "2020-06-01 21:37:25.5213906"
                        },
                        new
                        {
                            PaymentId = 49,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 10,
                            TimePaid = "2020-06-01 21:37:25.5213908"
                        },
                        new
                        {
                            PaymentId = 50,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 10,
                            TimePaid = "2020-06-01 21:37:25.521391"
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.ResourceUsageRate", b =>
                {
                    b.Property<int>("ResourceUsageRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PeriodEnd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<string>("PeriodStart")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.HasKey("ResourceUsageRateId");

                    b.ToTable("ResourceUsageRates");

                    b.HasData(
                        new
                        {
                            ResourceUsageRateId = 1,
                            PeriodEnd = "2020-11-29 21:37:25.520932",
                            PeriodStart = "2019-12-05 21:37:25.5059952",
                            Rate = 40.450000000000003,
                            ResourceType = 2
                        },
                        new
                        {
                            ResourceUsageRateId = 2,
                            PeriodEnd = "2020-11-29 21:37:25.5210156",
                            PeriodStart = "2019-12-05 21:37:25.5059952",
                            Rate = 3.4500000000000002,
                            ResourceType = 0
                        },
                        new
                        {
                            ResourceUsageRateId = 3,
                            PeriodEnd = "2020-11-29 21:37:25.521018",
                            PeriodStart = "2019-12-05 21:37:25.5059952",
                            Rate = 1100.0,
                            ResourceType = 4
                        },
                        new
                        {
                            ResourceUsageRateId = 4,
                            PeriodEnd = "2020-11-29 21:37:25.5210183",
                            PeriodStart = "2019-12-05 21:37:25.5059952",
                            Rate = 20.550000000000001,
                            ResourceType = 3
                        },
                        new
                        {
                            ResourceUsageRateId = 5,
                            PeriodEnd = "2020-11-29 21:37:25.5210185",
                            PeriodStart = "2019-12-05 21:37:25.5059952",
                            Rate = 1.75,
                            ResourceType = 1
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.SignedAgreement", b =>
                {
                    b.Property<int>("SignedAgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgreementId")
                        .HasColumnType("int");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<string>("SignedDate")
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("SignedAgreementId");

                    b.ToTable("SignedAgreements");

                    b.HasData(
                        new
                        {
                            SignedAgreementId = 1,
                            AgreementId = 1,
                            EndDate = "2020-06-02 21:37:25.5206164",
                            SignedDate = "2020-03-04 21:37:25.5059952",
                            StartDate = "2020-03-04 21:37:25.5059952",
                            TenantId = 1
                        },
                        new
                        {
                            SignedAgreementId = 2,
                            AgreementId = 2,
                            EndDate = "2020-06-02 21:37:25.5206998",
                            SignedDate = "2019-12-05 21:37:25.5059952",
                            StartDate = "2019-12-05 21:37:25.5059952",
                            TenantId = 2
                        },
                        new
                        {
                            SignedAgreementId = 3,
                            AgreementId = 3,
                            EndDate = "2020-06-02 21:37:25.5207024",
                            SignedDate = "2019-06-08 21:37:25.5059952",
                            StartDate = "2019-06-08 21:37:25.5059952",
                            TenantId = 3
                        },
                        new
                        {
                            SignedAgreementId = 4,
                            AgreementId = 1,
                            EndDate = "2020-06-02 21:37:25.5207028",
                            SignedDate = "2020-03-04 21:37:25.5059952",
                            StartDate = "2020-03-04 21:37:25.5059952",
                            TenantId = 4
                        },
                        new
                        {
                            SignedAgreementId = 5,
                            AgreementId = 2,
                            EndDate = "2020-06-02 21:37:25.520703",
                            SignedDate = "2019-12-05 21:37:25.5059952",
                            StartDate = "2019-12-05 21:37:25.5059952",
                            TenantId = 5
                        },
                        new
                        {
                            SignedAgreementId = 6,
                            AgreementId = 3,
                            EndDate = "2020-06-02 21:37:25.5207032",
                            SignedDate = "2019-06-08 21:37:25.5059952",
                            StartDate = "2019-06-08 21:37:25.5059952",
                            TenantId = 6
                        },
                        new
                        {
                            SignedAgreementId = 7,
                            AgreementId = 1,
                            EndDate = "2020-06-02 21:37:25.5207035",
                            SignedDate = "2020-03-04 21:37:25.5059952",
                            StartDate = "2020-03-04 21:37:25.5059952",
                            TenantId = 7
                        },
                        new
                        {
                            SignedAgreementId = 8,
                            AgreementId = 2,
                            EndDate = "2020-06-02 21:37:25.5207037",
                            SignedDate = "2019-12-05 21:37:25.5059952",
                            StartDate = "2019-12-05 21:37:25.5059952",
                            TenantId = 8
                        },
                        new
                        {
                            SignedAgreementId = 9,
                            AgreementId = 3,
                            EndDate = "2020-06-02 21:37:25.520704",
                            SignedDate = "2019-06-08 21:37:25.5059952",
                            StartDate = "2019-06-08 21:37:25.5059952",
                            TenantId = 9
                        },
                        new
                        {
                            SignedAgreementId = 10,
                            AgreementId = 1,
                            EndDate = "2020-06-02 21:37:25.5207042",
                            SignedDate = "2020-03-04 21:37:25.5059952",
                            StartDate = "2020-03-04 21:37:25.5059952",
                            TenantId = 10
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = 1,
                            Email = "jayson@gmail.com",
                            FirstName = "Jayson",
                            LastName = "Lennon",
                            PhoneNumber = "555-164-317",
                            UserId = 3
                        },
                        new
                        {
                            TenantId = 2,
                            Email = "david@gmail.com",
                            FirstName = "David",
                            LastName = "Sawyer",
                            PhoneNumber = "555-195-162",
                            UserId = 4
                        },
                        new
                        {
                            TenantId = 3,
                            Email = "michael@gmail.com",
                            FirstName = "Michael",
                            LastName = "Walker",
                            PhoneNumber = "555-115-412",
                            UserId = 5
                        },
                        new
                        {
                            TenantId = 4,
                            Email = "sulav@gmail.com",
                            FirstName = "Sulav",
                            LastName = "Aryal",
                            PhoneNumber = "555-787-595",
                            UserId = 6
                        },
                        new
                        {
                            TenantId = 5,
                            Email = "melvin@gmail.com",
                            FirstName = "Melvin",
                            LastName = "Johnson",
                            PhoneNumber = "555-858-445",
                            UserId = 7
                        },
                        new
                        {
                            TenantId = 6,
                            Email = "deon@gmail.com",
                            FirstName = "Deon ",
                            LastName = "Smith",
                            PhoneNumber = "555-514-298",
                            UserId = 8
                        },
                        new
                        {
                            TenantId = 7,
                            Email = "ruth@gmail.com",
                            FirstName = "Ruth ",
                            LastName = "Williams",
                            PhoneNumber = "555-337-777",
                            UserId = 9
                        },
                        new
                        {
                            TenantId = 8,
                            Email = "frances@gmail.com",
                            FirstName = "Frances ",
                            LastName = "Hook",
                            PhoneNumber = "555-871-503",
                            UserId = 10
                        },
                        new
                        {
                            TenantId = 9,
                            Email = "linda@gmail.com",
                            FirstName = "Linda",
                            LastName = "Lopez",
                            PhoneNumber = "555-607-558",
                            UserId = 11
                        },
                        new
                        {
                            TenantId = 10,
                            Email = "regina@gmail.com",
                            FirstName = "Regina",
                            LastName = "McCoy",
                            PhoneNumber = "555-504-625",
                            UserId = 12
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.TenantResourceUsage", b =>
                {
                    b.Property<int>("TenantResourceUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<string>("SampleTime")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<double>("UsageAmount")
                        .HasColumnType("float");

                    b.HasKey("TenantResourceUsageId");

                    b.ToTable("TenantResourceUsages");

                    b.HasData(
                        new
                        {
                            TenantResourceUsageId = 1,
                            ResourceType = 2,
                            SampleTime = "2020-06-01 21:37:25.520259",
                            TenantId = 1,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 2,
                            ResourceType = 0,
                            SampleTime = "2020-06-01 21:37:25.5203105",
                            TenantId = 1,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 3,
                            ResourceType = 4,
                            SampleTime = "2020-06-01 21:37:25.5203124",
                            TenantId = 1,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 4,
                            ResourceType = 3,
                            SampleTime = "2020-06-01 21:37:25.5203127",
                            TenantId = 1,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 5,
                            ResourceType = 1,
                            SampleTime = "2020-06-01 21:37:25.520313",
                            TenantId = 1,
                            UsageAmount = 40.399999999999999
                        },
                        new
                        {
                            TenantResourceUsageId = 6,
                            ResourceType = 2,
                            SampleTime = "2020-06-01 21:37:25.5203133",
                            TenantId = 2,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 7,
                            ResourceType = 0,
                            SampleTime = "2020-06-01 21:37:25.5203135",
                            TenantId = 2,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 8,
                            ResourceType = 4,
                            SampleTime = "2020-06-01 21:37:25.5203138",
                            TenantId = 2,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 9,
                            ResourceType = 3,
                            SampleTime = "2020-06-01 21:37:25.520314",
                            TenantId = 2,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 10,
                            ResourceType = 1,
                            SampleTime = "2020-06-01 21:37:25.5203143",
                            TenantId = 2,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 11,
                            ResourceType = 2,
                            SampleTime = "2020-06-01 21:37:25.5203146",
                            TenantId = 3,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 12,
                            ResourceType = 0,
                            SampleTime = "2020-06-01 21:37:25.5203149",
                            TenantId = 3,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 13,
                            ResourceType = 4,
                            SampleTime = "2020-06-01 21:37:25.5203151",
                            TenantId = 3,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 14,
                            ResourceType = 3,
                            SampleTime = "2020-06-01 21:37:25.5203154",
                            TenantId = 3,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 15,
                            ResourceType = 1,
                            SampleTime = "2020-06-01 21:37:25.5203156",
                            TenantId = 3,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 16,
                            ResourceType = 2,
                            SampleTime = "2020-06-01 21:37:25.5203158",
                            TenantId = 4,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 17,
                            ResourceType = 0,
                            SampleTime = "2020-06-01 21:37:25.5203161",
                            TenantId = 4,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 18,
                            ResourceType = 4,
                            SampleTime = "2020-06-01 21:37:25.5203163",
                            TenantId = 4,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 19,
                            ResourceType = 3,
                            SampleTime = "2020-06-01 21:37:25.5203165",
                            TenantId = 4,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 20,
                            ResourceType = 1,
                            SampleTime = "2020-06-01 21:37:25.5203168",
                            TenantId = 4,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 21,
                            ResourceType = 2,
                            SampleTime = "2020-06-01 21:37:25.5203171",
                            TenantId = 5,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 22,
                            ResourceType = 0,
                            SampleTime = "2020-06-01 21:37:25.5203173",
                            TenantId = 5,
                            UsageAmount = 60.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 23,
                            ResourceType = 4,
                            SampleTime = "2020-06-01 21:37:25.5203176",
                            TenantId = 5,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 24,
                            ResourceType = 3,
                            SampleTime = "2020-06-01 21:37:25.5203178",
                            TenantId = 5,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 25,
                            ResourceType = 1,
                            SampleTime = "2020-06-01 21:37:25.5203181",
                            TenantId = 5,
                            UsageAmount = 40.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 26,
                            ResourceType = 2,
                            SampleTime = "2020-06-01 21:37:25.5203183",
                            TenantId = 6,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 27,
                            ResourceType = 0,
                            SampleTime = "2020-06-01 21:37:25.5203185",
                            TenantId = 6,
                            UsageAmount = 60.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 28,
                            ResourceType = 4,
                            SampleTime = "2020-06-01 21:37:25.5203188",
                            TenantId = 6,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 29,
                            ResourceType = 3,
                            SampleTime = "2020-06-01 21:37:25.520319",
                            TenantId = 6,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 30,
                            ResourceType = 1,
                            SampleTime = "2020-06-01 21:37:25.5203193",
                            TenantId = 6,
                            UsageAmount = 31.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 31,
                            ResourceType = 2,
                            SampleTime = "2020-06-01 21:37:25.5203195",
                            TenantId = 7,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 32,
                            ResourceType = 0,
                            SampleTime = "2020-06-01 21:37:25.5203198",
                            TenantId = 7,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 33,
                            ResourceType = 4,
                            SampleTime = "2020-06-01 21:37:25.52032",
                            TenantId = 7,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 34,
                            ResourceType = 3,
                            SampleTime = "2020-06-01 21:37:25.5203203",
                            TenantId = 7,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 35,
                            ResourceType = 1,
                            SampleTime = "2020-06-01 21:37:25.5203205",
                            TenantId = 7,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 36,
                            ResourceType = 2,
                            SampleTime = "2020-06-01 21:37:25.5203208",
                            TenantId = 8,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 37,
                            ResourceType = 0,
                            SampleTime = "2020-06-01 21:37:25.520321",
                            TenantId = 8,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 38,
                            ResourceType = 4,
                            SampleTime = "2020-06-01 21:37:25.5203213",
                            TenantId = 8,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 39,
                            ResourceType = 3,
                            SampleTime = "2020-06-01 21:37:25.5203215",
                            TenantId = 8,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 40,
                            ResourceType = 1,
                            SampleTime = "2020-06-01 21:37:25.5203217",
                            TenantId = 8,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 41,
                            ResourceType = 2,
                            SampleTime = "2020-06-01 21:37:25.520322",
                            TenantId = 9,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 42,
                            ResourceType = 0,
                            SampleTime = "2020-06-01 21:37:25.5203222",
                            TenantId = 9,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 43,
                            ResourceType = 4,
                            SampleTime = "2020-06-01 21:37:25.5203224",
                            TenantId = 9,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 44,
                            ResourceType = 3,
                            SampleTime = "2020-06-01 21:37:25.5203227",
                            TenantId = 9,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 45,
                            ResourceType = 1,
                            SampleTime = "2020-06-01 21:37:25.5203229",
                            TenantId = 9,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 46,
                            ResourceType = 2,
                            SampleTime = "2020-06-01 21:37:25.5203231",
                            TenantId = 10,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 47,
                            ResourceType = 0,
                            SampleTime = "2020-06-01 21:37:25.5203234",
                            TenantId = 10,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 48,
                            ResourceType = 4,
                            SampleTime = "2020-06-01 21:37:25.5203236",
                            TenantId = 10,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 49,
                            ResourceType = 3,
                            SampleTime = "2020-06-01 21:37:25.5203239",
                            TenantId = 10,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 50,
                            ResourceType = 1,
                            SampleTime = "2020-06-01 21:37:25.5203242",
                            TenantId = 10,
                            UsageAmount = 30.329999999999998
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("UnitNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UnitId");

                    b.HasIndex("UnitNumber")
                        .IsUnique()
                        .HasFilter("[UnitNumber] IS NOT NULL");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            TenantId = 1,
                            UnitNumber = "101"
                        },
                        new
                        {
                            UnitId = 2,
                            TenantId = 2,
                            UnitNumber = "102"
                        },
                        new
                        {
                            UnitId = 3,
                            TenantId = 3,
                            UnitNumber = "103"
                        },
                        new
                        {
                            UnitId = 4,
                            TenantId = 4,
                            UnitNumber = "104"
                        },
                        new
                        {
                            UnitId = 5,
                            TenantId = 5,
                            UnitNumber = "105"
                        },
                        new
                        {
                            UnitId = 6,
                            TenantId = 6,
                            UnitNumber = "106"
                        },
                        new
                        {
                            UnitId = 7,
                            TenantId = 7,
                            UnitNumber = "107"
                        },
                        new
                        {
                            UnitId = 8,
                            TenantId = 8,
                            UnitNumber = "108"
                        },
                        new
                        {
                            UnitId = 9,
                            TenantId = 9,
                            UnitNumber = "109"
                        },
                        new
                        {
                            UnitId = 10,
                            TenantId = 10,
                            UnitNumber = "110"
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ApiKey = "test-key1",
                            FirstName = "admin",
                            LastName = "admin",
                            LoginName = "admin",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            ApiKey = "test-key2",
                            FirstName = "manager",
                            LastName = "manager",
                            LoginName = "manager",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Manager"
                        },
                        new
                        {
                            UserId = 3,
                            ApiKey = "test-key3",
                            FirstName = "jayson",
                            LastName = "",
                            LoginName = "jayson",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 4,
                            ApiKey = "test-key4",
                            FirstName = "david",
                            LastName = "",
                            LoginName = "david",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 5,
                            ApiKey = "test-key5",
                            FirstName = "michael",
                            LastName = "",
                            LoginName = "michael",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 6,
                            ApiKey = "test-key6",
                            FirstName = "sulav",
                            LastName = "",
                            LoginName = "sulav",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 7,
                            ApiKey = "test-key7",
                            FirstName = "melvin",
                            LastName = "",
                            LoginName = "melvin",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 8,
                            ApiKey = "test-key8",
                            FirstName = "deon",
                            LastName = "",
                            LoginName = "deon",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 9,
                            ApiKey = "test-key9",
                            FirstName = "ruth",
                            LastName = "",
                            LoginName = "ruth",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 10,
                            ApiKey = "test-key10",
                            FirstName = "frances",
                            LastName = "",
                            LoginName = "frances",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 11,
                            ApiKey = "test-key11",
                            FirstName = "linda",
                            LastName = "",
                            LoginName = "linda",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 12,
                            ApiKey = "test-key12",
                            FirstName = "regina",
                            LastName = "",
                            LoginName = "regina",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 13,
                            ApiKey = "test-key13",
                            FirstName = "sulav2",
                            LastName = "",
                            LoginName = "sulav2",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
