// <auto-generated />
using System;
using AptMgmtPortalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AptMgmtPortalAPI.Migrations.SqliteMigrations
{
    [DbContext(typeof(TestAptMgmtDbContext))]
    [Migration("20200602222049_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.Agreement", b =>
                {
                    b.Property<int>("AgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("AgreementId");

                    b.ToTable("Agreements");

                    b.HasData(
                        new
                        {
                            AgreementId = 1,
                            Text = "This is a really long lease agreement text",
                            Title = "Lease Agreement"
                        },
                        new
                        {
                            AgreementId = 2,
                            Text = "This is a really long utility agreement text",
                            Title = "Utility Agreement"
                        },
                        new
                        {
                            AgreementId = 3,
                            Text = "This is a really long internet connection agreement text",
                            Title = "Internet Connection Agreement"
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.BillingPeriod", b =>
                {
                    b.Property<int>("BillingPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("NVARCHAR(48)");

                    b.HasKey("BillingPeriodId");

                    b.ToTable("BillingPeriods");

                    b.HasData(
                        new
                        {
                            BillingPeriodId = 1,
                            PeriodEnd = new DateTime(2020, 6, 3, 15, 20, 48, 663, DateTimeKind.Local).AddTicks(3714),
                            PeriodStart = new DateTime(2020, 5, 3, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396)
                        },
                        new
                        {
                            BillingPeriodId = 2,
                            PeriodEnd = new DateTime(2020, 6, 3, 15, 20, 48, 663, DateTimeKind.Local).AddTicks(4156),
                            PeriodStart = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396)
                        },
                        new
                        {
                            BillingPeriodId = 3,
                            PeriodEnd = new DateTime(2020, 6, 3, 15, 20, 48, 663, DateTimeKind.Local).AddTicks(4177),
                            PeriodStart = new DateTime(2019, 12, 5, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396)
                        },
                        new
                        {
                            BillingPeriodId = 4,
                            PeriodEnd = new DateTime(2020, 6, 3, 15, 20, 48, 663, DateTimeKind.Local).AddTicks(4180),
                            PeriodStart = new DateTime(2019, 6, 8, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396)
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.MaintenanceRequest", b =>
                {
                    b.Property<int>("MaintenanceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloseReason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClosingUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceRequestType")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenNotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OpeningUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeClosed")
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<DateTime>("TimeOpened")
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<string>("UnitNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("MaintenanceRequestId");

                    b.ToTable("MaintenanceRequests");

                    b.HasData(
                        new
                        {
                            MaintenanceRequestId = 1,
                            CloseReason = "Completed",
                            ClosingUserId = 1,
                            InternalNotes = "Call Plumber",
                            MaintenanceRequestType = "Plumbing",
                            OpenNotes = "No water",
                            OpeningUserId = 1,
                            ResolutionNotes = "Fully restored.",
                            TimeClosed = new DateTime(2020, 6, 2, 15, 20, 48, 663, DateTimeKind.Local).AddTicks(749),
                            TimeOpened = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            UnitNumber = "101"
                        },
                        new
                        {
                            MaintenanceRequestId = 2,
                            CloseReason = "Completed",
                            ClosingUserId = 1,
                            InternalNotes = "Call Comcast",
                            OpenNotes = "No Interet",
                            OpeningUserId = 1,
                            ResolutionNotes = "Fixed",
                            TimeClosed = new DateTime(2020, 5, 3, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TimeOpened = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            UnitNumber = "101"
                        },
                        new
                        {
                            MaintenanceRequestId = 3,
                            CloseReason = "CanceledByManagement",
                            ClosingUserId = 1,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 1,
                            ResolutionNotes = "Fixed",
                            TimeClosed = new DateTime(2020, 5, 3, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TimeOpened = new DateTime(2019, 12, 5, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            UnitNumber = "101"
                        },
                        new
                        {
                            MaintenanceRequestId = 4,
                            CloseReason = "CanceledByTenant",
                            ClosingUserId = 1,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 2,
                            ResolutionNotes = "Fixed",
                            TimeClosed = new DateTime(2020, 5, 3, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TimeOpened = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            UnitNumber = "102"
                        },
                        new
                        {
                            MaintenanceRequestId = 5,
                            CloseReason = "CanceledByManagement",
                            ClosingUserId = 2,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 3,
                            ResolutionNotes = "Fixed",
                            TimeClosed = new DateTime(2020, 5, 3, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TimeOpened = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            UnitNumber = "103"
                        },
                        new
                        {
                            MaintenanceRequestId = 6,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 4,
                            TimeOpened = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            UnitNumber = "104"
                        },
                        new
                        {
                            MaintenanceRequestId = 7,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 5,
                            TimeOpened = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            UnitNumber = "105"
                        },
                        new
                        {
                            MaintenanceRequestId = 8,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 6,
                            TimeOpened = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            UnitNumber = "106"
                        },
                        new
                        {
                            MaintenanceRequestId = 9,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 7,
                            TimeOpened = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            UnitNumber = "107"
                        },
                        new
                        {
                            MaintenanceRequestId = 10,
                            InternalNotes = "Call Plumber",
                            OpenNotes = "No water",
                            OpeningUserId = 8,
                            TimeOpened = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            UnitNumber = "108"
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("BillingPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimePaid")
                        .HasColumnType("NVARCHAR(48)");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 1,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5462)
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 1,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5939)
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 1,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5959)
                        },
                        new
                        {
                            PaymentId = 4,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 1,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5963)
                        },
                        new
                        {
                            PaymentId = 5,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 1,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5965)
                        },
                        new
                        {
                            PaymentId = 6,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 2,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5967)
                        },
                        new
                        {
                            PaymentId = 7,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 2,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5970)
                        },
                        new
                        {
                            PaymentId = 8,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 2,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5973)
                        },
                        new
                        {
                            PaymentId = 9,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 2,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5975)
                        },
                        new
                        {
                            PaymentId = 10,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 2,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5978)
                        },
                        new
                        {
                            PaymentId = 11,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 3,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5980)
                        },
                        new
                        {
                            PaymentId = 12,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 3,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5983)
                        },
                        new
                        {
                            PaymentId = 13,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 3,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5985)
                        },
                        new
                        {
                            PaymentId = 14,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 3,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5987)
                        },
                        new
                        {
                            PaymentId = 15,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 3,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5990)
                        },
                        new
                        {
                            PaymentId = 16,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 4,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5992)
                        },
                        new
                        {
                            PaymentId = 17,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 4,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5994)
                        },
                        new
                        {
                            PaymentId = 18,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 4,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5997)
                        },
                        new
                        {
                            PaymentId = 19,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 4,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(5999)
                        },
                        new
                        {
                            PaymentId = 20,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 4,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6002)
                        },
                        new
                        {
                            PaymentId = 21,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 5,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6004)
                        },
                        new
                        {
                            PaymentId = 22,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 5,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6007)
                        },
                        new
                        {
                            PaymentId = 23,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 5,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6009)
                        },
                        new
                        {
                            PaymentId = 24,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 5,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6011)
                        },
                        new
                        {
                            PaymentId = 25,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 5,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6014)
                        },
                        new
                        {
                            PaymentId = 26,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 6,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6016)
                        },
                        new
                        {
                            PaymentId = 27,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 6,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6018)
                        },
                        new
                        {
                            PaymentId = 28,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 6,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6021)
                        },
                        new
                        {
                            PaymentId = 29,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 6,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6023)
                        },
                        new
                        {
                            PaymentId = 30,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 6,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6025)
                        },
                        new
                        {
                            PaymentId = 31,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 7,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6028)
                        },
                        new
                        {
                            PaymentId = 32,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 7,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6030)
                        },
                        new
                        {
                            PaymentId = 33,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 7,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6032)
                        },
                        new
                        {
                            PaymentId = 34,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 7,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6034)
                        },
                        new
                        {
                            PaymentId = 35,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 7,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6037)
                        },
                        new
                        {
                            PaymentId = 36,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 8,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6039)
                        },
                        new
                        {
                            PaymentId = 37,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 8,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6041)
                        },
                        new
                        {
                            PaymentId = 38,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 8,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6044)
                        },
                        new
                        {
                            PaymentId = 39,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 8,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6048)
                        },
                        new
                        {
                            PaymentId = 40,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 8,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6050)
                        },
                        new
                        {
                            PaymentId = 41,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 9,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6054)
                        },
                        new
                        {
                            PaymentId = 42,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 9,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6056)
                        },
                        new
                        {
                            PaymentId = 43,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 9,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6059)
                        },
                        new
                        {
                            PaymentId = 44,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 9,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6061)
                        },
                        new
                        {
                            PaymentId = 45,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 9,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6063)
                        },
                        new
                        {
                            PaymentId = 46,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 2,
                            TenantId = 10,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6066)
                        },
                        new
                        {
                            PaymentId = 47,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 0,
                            TenantId = 10,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6068)
                        },
                        new
                        {
                            PaymentId = 48,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 4,
                            TenantId = 10,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6070)
                        },
                        new
                        {
                            PaymentId = 49,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 3,
                            TenantId = 10,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6072)
                        },
                        new
                        {
                            PaymentId = 50,
                            Amount = 100.11,
                            BillingPeriodId = 1,
                            ResourceType = 1,
                            TenantId = 10,
                            TimePaid = new DateTime(2020, 6, 1, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(6075)
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.ResourceUsageRate", b =>
                {
                    b.Property<int>("ResourceUsageRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL");

                    b.Property<int>("ResourceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResourceUsageRateId");

                    b.ToTable("ResourceUsageRates");

                    b.HasData(
                        new
                        {
                            ResourceUsageRateId = 1,
                            PeriodEnd = new DateTime(2020, 11, 29, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(1242),
                            PeriodStart = new DateTime(2019, 12, 5, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            Rate = 40.450000000000003,
                            ResourceType = 2
                        },
                        new
                        {
                            ResourceUsageRateId = 2,
                            PeriodEnd = new DateTime(2020, 11, 29, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(2078),
                            PeriodStart = new DateTime(2019, 12, 5, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            Rate = 3.4500000000000002,
                            ResourceType = 0
                        },
                        new
                        {
                            ResourceUsageRateId = 3,
                            PeriodEnd = new DateTime(2020, 11, 29, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(2105),
                            PeriodStart = new DateTime(2019, 12, 5, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            Rate = 1100.0,
                            ResourceType = 4
                        },
                        new
                        {
                            ResourceUsageRateId = 4,
                            PeriodEnd = new DateTime(2020, 11, 29, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(2108),
                            PeriodStart = new DateTime(2019, 12, 5, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            Rate = 20.550000000000001,
                            ResourceType = 3
                        },
                        new
                        {
                            ResourceUsageRateId = 5,
                            PeriodEnd = new DateTime(2020, 11, 29, 15, 20, 48, 662, DateTimeKind.Local).AddTicks(2111),
                            PeriodStart = new DateTime(2019, 12, 5, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            Rate = 1.75,
                            ResourceType = 1
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.SignedAgreement", b =>
                {
                    b.Property<int>("SignedAgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgreementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<DateTime>("SignedDate")
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SignedAgreementId");

                    b.ToTable("SignedAgreements");

                    b.HasData(
                        new
                        {
                            SignedAgreementId = 1,
                            AgreementId = 1,
                            EndDate = new DateTime(2020, 6, 2, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(8124),
                            SignedDate = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            StartDate = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TenantId = 1
                        },
                        new
                        {
                            SignedAgreementId = 2,
                            AgreementId = 2,
                            EndDate = new DateTime(2020, 6, 2, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(8936),
                            SignedDate = new DateTime(2019, 12, 5, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            StartDate = new DateTime(2019, 12, 5, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TenantId = 2
                        },
                        new
                        {
                            SignedAgreementId = 3,
                            AgreementId = 3,
                            EndDate = new DateTime(2020, 6, 2, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(8964),
                            SignedDate = new DateTime(2019, 6, 8, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            StartDate = new DateTime(2019, 6, 8, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TenantId = 3
                        },
                        new
                        {
                            SignedAgreementId = 4,
                            AgreementId = 1,
                            EndDate = new DateTime(2020, 6, 2, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(8967),
                            SignedDate = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            StartDate = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TenantId = 4
                        },
                        new
                        {
                            SignedAgreementId = 5,
                            AgreementId = 2,
                            EndDate = new DateTime(2020, 6, 2, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(8970),
                            SignedDate = new DateTime(2019, 12, 5, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            StartDate = new DateTime(2019, 12, 5, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TenantId = 5
                        },
                        new
                        {
                            SignedAgreementId = 6,
                            AgreementId = 3,
                            EndDate = new DateTime(2020, 6, 2, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(8972),
                            SignedDate = new DateTime(2019, 6, 8, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            StartDate = new DateTime(2019, 6, 8, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TenantId = 6
                        },
                        new
                        {
                            SignedAgreementId = 7,
                            AgreementId = 1,
                            EndDate = new DateTime(2020, 6, 2, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(8975),
                            SignedDate = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            StartDate = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TenantId = 7
                        },
                        new
                        {
                            SignedAgreementId = 8,
                            AgreementId = 2,
                            EndDate = new DateTime(2020, 6, 2, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(8978),
                            SignedDate = new DateTime(2019, 12, 5, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            StartDate = new DateTime(2019, 12, 5, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TenantId = 8
                        },
                        new
                        {
                            SignedAgreementId = 9,
                            AgreementId = 3,
                            EndDate = new DateTime(2020, 6, 2, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(8981),
                            SignedDate = new DateTime(2019, 6, 8, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            StartDate = new DateTime(2019, 6, 8, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TenantId = 9
                        },
                        new
                        {
                            SignedAgreementId = 10,
                            AgreementId = 1,
                            EndDate = new DateTime(2020, 6, 2, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(8983),
                            SignedDate = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            StartDate = new DateTime(2020, 3, 4, 15, 20, 48, 654, DateTimeKind.Local).AddTicks(3396),
                            TenantId = 10
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = 1,
                            Email = "jayson@gmail.com",
                            FirstName = "Jayson",
                            LastName = "Lennon",
                            PhoneNumber = "555-164-317",
                            UserId = 3
                        },
                        new
                        {
                            TenantId = 2,
                            Email = "david@gmail.com",
                            FirstName = "David",
                            LastName = "Sawyer",
                            PhoneNumber = "555-195-162",
                            UserId = 4
                        },
                        new
                        {
                            TenantId = 3,
                            Email = "michael@gmail.com",
                            FirstName = "Michael",
                            LastName = "Walker",
                            PhoneNumber = "555-115-412",
                            UserId = 5
                        },
                        new
                        {
                            TenantId = 4,
                            Email = "sulav@gmail.com",
                            FirstName = "Sulav",
                            LastName = "Aryal",
                            PhoneNumber = "555-787-595",
                            UserId = 6
                        },
                        new
                        {
                            TenantId = 5,
                            Email = "melvin@gmail.com",
                            FirstName = "Melvin",
                            LastName = "Johnson",
                            PhoneNumber = "555-858-445",
                            UserId = 7
                        },
                        new
                        {
                            TenantId = 6,
                            Email = "deon@gmail.com",
                            FirstName = "Deon ",
                            LastName = "Smith",
                            PhoneNumber = "555-514-298",
                            UserId = 8
                        },
                        new
                        {
                            TenantId = 7,
                            Email = "ruth@gmail.com",
                            FirstName = "Ruth ",
                            LastName = "Williams",
                            PhoneNumber = "555-337-777",
                            UserId = 9
                        },
                        new
                        {
                            TenantId = 8,
                            Email = "frances@gmail.com",
                            FirstName = "Frances ",
                            LastName = "Hook",
                            PhoneNumber = "555-871-503",
                            UserId = 10
                        },
                        new
                        {
                            TenantId = 9,
                            Email = "linda@gmail.com",
                            FirstName = "Linda",
                            LastName = "Lopez",
                            PhoneNumber = "555-607-558",
                            UserId = 11
                        },
                        new
                        {
                            TenantId = 10,
                            Email = "regina@gmail.com",
                            FirstName = "Regina",
                            LastName = "McCoy",
                            PhoneNumber = "555-504-625",
                            UserId = 12
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.TenantResourceUsage", b =>
                {
                    b.Property<int>("TenantResourceUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SampleTime")
                        .HasColumnType("NVARCHAR(48)");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UsageAmount")
                        .HasColumnType("REAL");

                    b.HasKey("TenantResourceUsageId");

                    b.ToTable("TenantResourceUsages");

                    b.HasData(
                        new
                        {
                            TenantResourceUsageId = 1,
                            ResourceType = 2,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(4668),
                            TenantId = 1,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 2,
                            ResourceType = 0,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5284),
                            TenantId = 1,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 3,
                            ResourceType = 4,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5316),
                            TenantId = 1,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 4,
                            ResourceType = 3,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5319),
                            TenantId = 1,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 5,
                            ResourceType = 1,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5322),
                            TenantId = 1,
                            UsageAmount = 40.399999999999999
                        },
                        new
                        {
                            TenantResourceUsageId = 6,
                            ResourceType = 2,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5325),
                            TenantId = 2,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 7,
                            ResourceType = 0,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5327),
                            TenantId = 2,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 8,
                            ResourceType = 4,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5330),
                            TenantId = 2,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 9,
                            ResourceType = 3,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5333),
                            TenantId = 2,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 10,
                            ResourceType = 1,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5336),
                            TenantId = 2,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 11,
                            ResourceType = 2,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5339),
                            TenantId = 3,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 12,
                            ResourceType = 0,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5341),
                            TenantId = 3,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 13,
                            ResourceType = 4,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5344),
                            TenantId = 3,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 14,
                            ResourceType = 3,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5346),
                            TenantId = 3,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 15,
                            ResourceType = 1,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5348),
                            TenantId = 3,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 16,
                            ResourceType = 2,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5351),
                            TenantId = 4,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 17,
                            ResourceType = 0,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5353),
                            TenantId = 4,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 18,
                            ResourceType = 4,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5355),
                            TenantId = 4,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 19,
                            ResourceType = 3,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5358),
                            TenantId = 4,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 20,
                            ResourceType = 1,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5360),
                            TenantId = 4,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 21,
                            ResourceType = 2,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5362),
                            TenantId = 5,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 22,
                            ResourceType = 0,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5365),
                            TenantId = 5,
                            UsageAmount = 60.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 23,
                            ResourceType = 4,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5367),
                            TenantId = 5,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 24,
                            ResourceType = 3,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5369),
                            TenantId = 5,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 25,
                            ResourceType = 1,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5372),
                            TenantId = 5,
                            UsageAmount = 40.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 26,
                            ResourceType = 2,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5375),
                            TenantId = 6,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 27,
                            ResourceType = 0,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5378),
                            TenantId = 6,
                            UsageAmount = 60.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 28,
                            ResourceType = 4,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5380),
                            TenantId = 6,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 29,
                            ResourceType = 3,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5383),
                            TenantId = 6,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 30,
                            ResourceType = 1,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5386),
                            TenantId = 6,
                            UsageAmount = 31.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 31,
                            ResourceType = 2,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5388),
                            TenantId = 7,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 32,
                            ResourceType = 0,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5390),
                            TenantId = 7,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 33,
                            ResourceType = 4,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5393),
                            TenantId = 7,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 34,
                            ResourceType = 3,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5395),
                            TenantId = 7,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 35,
                            ResourceType = 1,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5397),
                            TenantId = 7,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 36,
                            ResourceType = 2,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5400),
                            TenantId = 8,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 37,
                            ResourceType = 0,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5402),
                            TenantId = 8,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 38,
                            ResourceType = 4,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5404),
                            TenantId = 8,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 39,
                            ResourceType = 3,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5407),
                            TenantId = 8,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 40,
                            ResourceType = 1,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5409),
                            TenantId = 8,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 41,
                            ResourceType = 2,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5411),
                            TenantId = 9,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 42,
                            ResourceType = 0,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5414),
                            TenantId = 9,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 43,
                            ResourceType = 4,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5417),
                            TenantId = 9,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 44,
                            ResourceType = 3,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5419),
                            TenantId = 9,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 45,
                            ResourceType = 1,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5421),
                            TenantId = 9,
                            UsageAmount = 30.329999999999998
                        },
                        new
                        {
                            TenantResourceUsageId = 46,
                            ResourceType = 2,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5424),
                            TenantId = 10,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 47,
                            ResourceType = 0,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5426),
                            TenantId = 10,
                            UsageAmount = 50.549999999999997
                        },
                        new
                        {
                            TenantResourceUsageId = 48,
                            ResourceType = 4,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5429),
                            TenantId = 10,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 49,
                            ResourceType = 3,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5432),
                            TenantId = 10,
                            UsageAmount = 1.0
                        },
                        new
                        {
                            TenantResourceUsageId = 50,
                            ResourceType = 1,
                            SampleTime = new DateTime(2020, 6, 1, 15, 20, 48, 661, DateTimeKind.Local).AddTicks(5435),
                            TenantId = 10,
                            UsageAmount = 30.329999999999998
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("UnitId");

                    b.HasIndex("UnitNumber")
                        .IsUnique();

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            UnitId = 1,
                            TenantId = 1,
                            UnitNumber = "101"
                        },
                        new
                        {
                            UnitId = 2,
                            TenantId = 2,
                            UnitNumber = "102"
                        },
                        new
                        {
                            UnitId = 3,
                            TenantId = 3,
                            UnitNumber = "103"
                        },
                        new
                        {
                            UnitId = 4,
                            TenantId = 4,
                            UnitNumber = "104"
                        },
                        new
                        {
                            UnitId = 5,
                            TenantId = 5,
                            UnitNumber = "105"
                        },
                        new
                        {
                            UnitId = 6,
                            TenantId = 6,
                            UnitNumber = "106"
                        },
                        new
                        {
                            UnitId = 7,
                            TenantId = 7,
                            UnitNumber = "107"
                        },
                        new
                        {
                            UnitId = 8,
                            TenantId = 8,
                            UnitNumber = "108"
                        },
                        new
                        {
                            UnitId = 9,
                            TenantId = 9,
                            UnitNumber = "109"
                        },
                        new
                        {
                            UnitId = 10,
                            TenantId = 10,
                            UnitNumber = "110"
                        });
                });

            modelBuilder.Entity("AptMgmtPortalAPI.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAccountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ApiKey = "test-key1",
                            FirstName = "admin",
                            LastName = "admin",
                            LoginName = "admin",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            ApiKey = "test-key2",
                            FirstName = "manager",
                            LastName = "manager",
                            LoginName = "manager",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Manager"
                        },
                        new
                        {
                            UserId = 3,
                            ApiKey = "test-key3",
                            FirstName = "jayson",
                            LastName = "",
                            LoginName = "jayson",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 4,
                            ApiKey = "test-key4",
                            FirstName = "david",
                            LastName = "",
                            LoginName = "david",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 5,
                            ApiKey = "test-key5",
                            FirstName = "michael",
                            LastName = "",
                            LoginName = "michael",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 6,
                            ApiKey = "test-key6",
                            FirstName = "sulav",
                            LastName = "",
                            LoginName = "sulav",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 7,
                            ApiKey = "test-key7",
                            FirstName = "melvin",
                            LastName = "",
                            LoginName = "melvin",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 8,
                            ApiKey = "test-key8",
                            FirstName = "deon",
                            LastName = "",
                            LoginName = "deon",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 9,
                            ApiKey = "test-key9",
                            FirstName = "ruth",
                            LastName = "",
                            LoginName = "ruth",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 10,
                            ApiKey = "test-key10",
                            FirstName = "frances",
                            LastName = "",
                            LoginName = "frances",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 11,
                            ApiKey = "test-key11",
                            FirstName = "linda",
                            LastName = "",
                            LoginName = "linda",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 12,
                            ApiKey = "test-key12",
                            FirstName = "regina",
                            LastName = "",
                            LoginName = "regina",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        },
                        new
                        {
                            UserId = 13,
                            ApiKey = "test-key13",
                            FirstName = "sulav2",
                            LastName = "",
                            LoginName = "sulav2",
                            Password = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg=",
                            UserAccountType = "Tenant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
